version: 2
jobs:  
  build:  
    docker:  
      - image: circleci/node:lts
    steps: 
      - run: 
          name: Build
          command: echo "build"
      - run:
          name: Run unit tests
          command: echo "unit tests"
      - run:
          name: Stage 3
          command: echo "deploy to host"
