version: 2
jobs:  
  build:  
    docker:  
      - image: circleci/node:lts
    steps: 
      - checkout
      - run:
          name: Install npm
          command: sudo apt install npm
      - run:
          name: Install npm
          command: sudo apt install npm
      - run: 
          name: Build
          command: npm run build
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Deploy
          command: echo "deploy to host"
